name: Deploy-test-2
on:
  push:
    branches: [ "main" ]

jobs:

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: kehoe/validate-configs-action@v4.0.1

    steps:
      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: | 
            sh ${{ secrets.PATH_TO_SCRIPT }}
