name: Production dso-test
on:
 push:
 branches: [main, develop]
jobs:
 deploy:
 runs-on: ubuntu-latest
    steps:
 - uses: Rxinui/ssh-deploy-repo-action@v1.1
        with:
 # Required
          ssh-user: alex
          ssh-password: ${{ secrets.NETOLOGY_SERVER_ALEX }}
          ssh-domain: ${{ secrets.OVH_HOSTING_DOMAIN }}
          # Optional
          git-clone-by: ssh
          target-branch: develop
          target-directory: ~/
          pre-command: | # multi-line script possible
 cd ~/; sh deploy.sh
# docker-compose down -v --remove-orphans;
# sh stop.sh
#          post-command: sh startup.sh
#docker-compose up -d -V --force-recreate
