name: Secrets Scanning

# Controls when the workflow will run

on:

 # Triggers the workflow on push or pull request events for the main branch

 push:

   branches: [ main ]

# Defining the job(s) to be run to execute secrets scanning

jobs:

 # This workflow contains a single job called "Scan-for-secrets"

 Scan-for-secrets:

   # The type of runner that the job will run on

   runs-on: ubuntu-latest

   # Steps define the order in which the tasks will be executed

   steps:

     # Checks-out the repository so our job can access it

     - uses: actions/checkout@v4

     # Installs secret scanner on the runner
     - name:  typing_extensions==4.7.1 --upgrade

       run: sudo pip install typing_extensions==4.7.1 --upgrade

     - name: Install Whispers

       run: sudo pip install whispers

     # Scan repo for secrets

     - name: Run scanner for the repository

       run: whispers ${{ github.workspace }} > /tmp/scan_output.json

     # Upload Artifacts

     - name: Upload the scan output

       uses: actions/upload-artifact@v4

       with:

         name: scan_results

         path: /tmp/scan_output.json

         retention-days: 2
