---
name: Secret Scan

on:
 pull_request:
 push:
 branches:
 - main

# allow one concurrency
concurrency:
 group: ${{ format('{0}-{1}-{2}-{3}-{4}', github.workflow, github.event_name, github.ref, github.base_ref, github.head_ref) }}
  cancel-in-progress: true

jobs:
 gitleaks:
 runs-on: ubuntu-latest
    steps:
      - name: Checkout
  uses: actions/checkout@v4
  with:
 fetch-depth: 0

- name: Run Gitleaks
  id: gitleaks
  uses: DariuszPorowski/github-action-gitleaks@v2
  with:
 report_format: sarif
    fail: false

# (optional) It's just to see outputs from the Action
# please note, the OUTPUT has to be passed via env vars!
name: Get the output from the gitleaks step
  run: |
 echo "exitcode: ${{ steps.gitleaks.outputs.exitcode }}"
 echo "result: ${{ steps.gitleaks.outputs.result }}"
 echo "command: ${{ steps.gitleaks.outputs.command }}"
 echo "report: ${{ steps.gitleaks.outputs.report }}"
 echo "output: ${GITLEAKS_OUTPUT}"
  env:
 GITLEAKS_OUTPUT: ${{ steps.gitleaks.outputs.output }}

name: Upload Gitleaks SARIF report to code scanning service
  if: ${{ steps.gitleaks.outputs.exitcode == 1 }}
  uses: github/codeql-action/upload-sarif@v3
  with:
 sarif_file: ${{ steps.gitleaks.outputs.report }}
