name: "Validate Configs"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '27 3 * * 3'

jobs:
  validate-config-files:
    runs-on: ubuntu-latest
    steps:
     - uses: kehoecj/validate-configs-action@v4.0.1
        with:
            depth: 0
            reporter: "json"
